"""Update wardrobe tag to top/bottom

Revision ID: 5603a1ccee77
Revises: 6ea5ea781554
Create Date: 2026-06-28 19:01:30.410802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5603a1ccee77'
down_revision = '6ea5ea781554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=mysql.ENUM('上衣', '下著', '連身', '外套', '配件'),
               type_=mysql.ENUM('top', 'bottom'),
               existing_comment='衣服分類標籤',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=mysql.ENUM('top', 'bottom'),
               type_=mysql.ENUM('上衣', '下著', '連身', '外套', '配件'),
               existing_comment='衣服分類標籤',
               existing_nullable=False)

    # ### end Alembic commands ###
