"""add timestamp in colors_for_type

Revision ID: 59df4eaf514b
Revises: 5603a1ccee77
Create Date: 2026-06-28 23:34:31.761078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59df4eaf514b'
down_revision = '5603a1ccee77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colors_for_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True, comment='建立時間戳記'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colors_for_type', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
