"""Init all tables

Revision ID: 6ea5ea781554
Revises: 
Create Date: 2026-06-28 18:21:08.031032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ea5ea781554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='季節唯一識別碼'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='季節名稱 (例如：春季型)'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='建立時間戳記'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='大季節分類表 (春、夏、秋、冬)'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='使用者唯一識別碼'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登入帳號名稱'),
    sa.Column('mail', sa.String(length=120), nullable=False, comment='聯絡與註冊信箱'),
    sa.Column('pwd', sa.String(length=255), nullable=False, comment='加密後的密碼 (Hash)'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='紀錄建立時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    comment='使用者基本資料表 (管理帳號密碼與個人資訊)'
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='型別唯一識別碼'),
    sa.Column('sid', sa.Integer(), nullable=False, comment='隸屬的大季節 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='型別名稱 (例如：淺春型)'),
    sa.Column('eng_name', sa.String(length=50), nullable=True, comment='英文型別名稱 (例如：Light Spring)'),
    sa.Column('description', sa.Text(), nullable=True, comment='該型別的特徵描述與穿搭建議'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='建立時間戳記'),
    sa.ForeignKeyConstraint(['sid'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='色彩型別表 (季節下的細分)'
    )
    op.create_table('wardrobe_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='單品唯一識別碼'),
    sa.Column('uid', sa.Integer(), nullable=False, comment='擁有此衣服的使用者 ID'),
    sa.Column('tag', mysql.ENUM('上衣', '下著', '連身', '外套', '配件'), nullable=False, comment='衣服分類標籤'),
    sa.Column('imgPath', sa.String(length=255), nullable=False, comment='圖片儲存路徑 (實體檔案路徑或雲端網址)'),
    sa.Column('color_1', sa.String(length=30), nullable=True, comment='KMeans 抓出的主要顏色 1 (RGB)'),
    sa.Column('color_2', sa.String(length=30), nullable=True, comment='KMeans 抓出的主要顏色 2 (RGB)'),
    sa.Column('color_3', sa.String(length=30), nullable=True, comment='KMeans 抓出的主要顏色 3 (RGB)'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='建立時間戳記'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='衣櫥單品資料表 (儲存使用者上傳並去背的衣服)'
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='診斷紀錄唯一識別碼'),
    sa.Column('uid', sa.Integer(), nullable=False, comment='受測使用者 ID'),
    sa.Column('faceImg', sa.String(length=255), nullable=False, comment='使用者用於分析的臉部照片路徑'),
    sa.Column('tid', sa.Integer(), nullable=False, comment='分析結果隸屬的色彩型別 ID'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='測色時間戳記'),
    sa.ForeignKeyConstraint(['tid'], ['types.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='PCA 診斷紀錄表 (儲存使用者每次的測色結果)'
    )
    op.create_table('colors_for_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='顏色識別碼'),
    sa.Column('tid', sa.Integer(), nullable=False, comment='對應的色彩型別 ID'),
    sa.Column('label', sa.String(length=50), nullable=True, comment='適合的顏色值（色碼標籤）'),
    sa.Column('color', sa.String(length=30), nullable=False, comment='適合的顏色值 (HEX 或 RGB)'),
    sa.ForeignKeyConstraint(['tid'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='色彩庫 (定義各型別適合的具體顏色)'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colors_for_type')
    op.drop_table('analysis_results')
    op.drop_table('wardrobe_items')
    op.drop_table('types')
    op.drop_table('users')
    op.drop_table('seasons')
    # ### end Alembic commands ###
